myapp/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from .views import  Homepage
from django.contrib.auth import views as auth_views


app_name = "main"


urlpatterns = [
    path('', Homepage.as_view(), name="homepage"),
    #path('mail/', Mail.as_view(), name="mail"),
    


    path("login/", auth_views.LoginView.as_view(template_name='main/login_page.html'), name='login_request'),

    path("logout/", auth_views.LogoutView.as_view(template_name='main/logout_page.html'), name='logout_request'),

    path("register_user/", views.register_user, name='register_user'),

    #path("change_password/", PasswordChange.as_view(success_url=reverse_lazy('main:login_request'),template_name='main/change_password.html'), name='change_password'),

    
    

    

] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

myapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin



class Homepage(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):
        return render(request, 'main/start_page.html')

def register_user(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data["username"]
			password = form.cleaned_data["password1"]
			user = authenticate(username=username,password=password)
			login(request,user)
			messages.success(request, ("Registration Success!"))
			return redirect("main:homepage")
	else:
		form = UserCreationForm()
	return render(request, "auth/register_user.html", {"form":form})

myapp/templates/main/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #096979;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #1a7909
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #1a7909,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}


    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        <h3>Login Here</h3>

       {% csrf_token %}
				{{ form.as_p }}
				<br>
				<button type="submit">Login
				</button>
        
    </form>
</body>
</html>

myapp/templates/main/logout_page.html
    {% load static %}
  <!DOCTYPE html>
  <html>
  <head>
    <title>LogOut Page</title>
    <style type="text/css">
   body {
    background-color: #096979;
    
   }
.content {
  background-color: #096979;
  width: 50%;
  padding: 40px;
  margin: 100px auto;
  font-family: calibri;
  border-radius: 10px;
}
p{
  font-size: 30px;
  color: white;

}

body {
  background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
  height: 100vh;
}

@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}


  </style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  <link rel="stylesheet" type="text/css" href="{% static 'pird/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!--for datatable-->

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css"/>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>
  <script src="{% static 'pird/employee_datatable.js' %}"></script>

<!--- RETURN TO LOGIN PAGE VALIDATION --->

  <script>
function validate(){
alert ("Do you Wish to return to the Login Page ?");
window.location = "{% url 'main:login_request' %}"; 
return false;
}
</script>

  </head>
  <body>

    
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <center>  
  <div class="container">
  <div class="form-group">
    <!--
    <img src="{% static 'pictures/back.jpg' %}">
  -->
  <center>
          <br>
       
        <br>
  <p>

  <H2>You Have Been Logged Out !</H2>
  </p>
  <br>
 <a class="btn btn-primary" id="submit" onclick="validate()" >Log Back Here&nbsp;&nbsp;</a>
</div>
</div>
</center>


  </body>
  </html>

myapp/templates/main/start_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>HR Pieroll System</title>


   <!-- bootstratp -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

   <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>


    <!-- /bootstratp -->

  <!--jquery-->

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https:///cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"/>

  <script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
  <!--/jquery-->
  <!--custom css-->
  <link rel="stylesheet" type="text/css" href=" {% static 'css/main_css.css' %} ">
  <!--/custom css-->

</head>


{% if user.is_authenticated == False %}
<body>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{% static 'pictures/invo.png' %}" alt="Bootstrap" width="30" height="24">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        
      </ul>
      <a href="{% url 'main:login_request' %}" class="btn btn-primary">Login</a>
      <a href="{% url 'main:register_user' %}" class="btn btn-primary">Register</a>
    </div>
  </div>
</nav>
<h1>Please Login</h1>
</body>
{% elif user.is_authenticated %}

<body class="homepage_body">
<div>
  <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{% static 'pictures/invo.png' %}" alt="Bootstrap" width="30" height="24">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Dashboard</a>
                    </li>
                    
                    
                    
                    <div class="pull-right">
                            <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:logout_request' %}">Logout</a>
                            </li>
                            </div>

                </ul>

            </div>
        </div>
    </nav>
</div>


<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Welcome!</h4>
    <p>You are now logged in!</p>

    
</div>

</body>
{% endif %}



<script src="{% static 'javascript/main_js.js' %}"></script>
</html>